const fs = require('fs');
const path = 'app/src/main/java/com/mhub/app/ui/social/SocialScreens.kt';
let c = fs.readFileSync(path, 'utf8');

const start = c.indexOf('\r\n@Composable\r\nprivate fun FeedCard(');
const end = c.indexOf('\r\n// FeedDetailScreen', start);

if (start < 0 || end < 0) {
  console.log('ERROR: markers not found, start=' + start + ' end=' + end);
  process.exit(1);
}

console.log('Found FeedCard at ' + start + ' to ' + end);

// Build new card content as an array to avoid JS template literal issues with Kotlin $ syntax
var lines = [];
lines.push('@Composable');
lines.push('private fun FeedCard(item: FeedItem, onClick: (() -> Unit)? = null, onPromote: (() -> Unit)? = null, onShare: (() -> Unit)? = null) {');
lines.push('    var expanded by remember { mutableStateOf(false) }');
lines.push('    var localLiked by remember { mutableStateOf(false) }');
lines.push('    val context = LocalContext.current');
lines.push('    val haptic = LocalHapticFeedback.current');
lines.push('    val likeScale by animateFloatAsState(');
lines.push('        targetValue = if (localLiked) 1.15f else 1.0f,');
lines.push('        animationSpec = spring(dampingRatio = Spring.DampingRatioMediumBouncy, stiffness = Spring.StiffnessMedium),');
lines.push('        label = "like_scale",');
lines.push('    )');
lines.push('    Surface(');
lines.push('        shape = RoundedCornerShape(16.dp),');
lines.push('        color = MaterialTheme.colorScheme.surface,');
lines.push('        tonalElevation = 1.dp,');
lines.push('        modifier = Modifier.fillMaxWidth().then(if (onClick != null) Modifier.clickable(onClick = onClick) else Modifier),');
lines.push('    ) {');
lines.push('        Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {');
lines.push('            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(10.dp)) {');
lines.push('                val initial = (item.displayName.firstOrNull() ?: \'M\').uppercaseChar().toString()');
lines.push('                val avatarGrads = listOf(');
lines.push('                    Color(0xFF818CF8) to Color(0xFFA855F7),');
lines.push('                    Color(0xFF34D399) to Color(0xFF14B8A6),');
lines.push('                    Color(0xFFFBBF24) to Color(0xFFF97316),');
lines.push('                    Color(0xFFF472B6) to Color(0xFFF43F5E),');
lines.push('                    Color(0xFF38BDF8) to Color(0xFF3B82F6),');
lines.push('                )');
lines.push('                var hash = 0');
lines.push('                for (ch in item.displayName) { hash = (hash * 31 + ch.code) % 100000 }');
lines.push('                val (avatarStart, avatarEnd) = avatarGrads[Math.abs(hash) % avatarGrads.size]');
lines.push('                Box(');
lines.push('                    modifier = Modifier.size(40.dp).clip(CircleShape).background(Brush.linearGradient(listOf(avatarStart, avatarEnd))),');
lines.push('                    contentAlignment = Alignment.Center,');
lines.push('                ) { Text(initial, color = Color.White, fontWeight = FontWeight.Bold, fontSize = 16.sp) }');
lines.push('                Column(Modifier.weight(1f)) {');
lines.push('                    Text(item.displayName, fontWeight = FontWeight.SemiBold, fontSize = 14.sp, color = MaterialTheme.colorScheme.onSurface)');
lines.push('                    Text(item.createdAt?.take(10) ?: "", fontSize = 11.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)');
lines.push('                }');
lines.push('                var showMore by remember { mutableStateOf(false) }');
lines.push('                Box {');
lines.push('                    IconButton(onClick = { showMore = true }, modifier = Modifier.size(32.dp)) {');
lines.push('                        Icon(Icons.Default.MoreVert, null, tint = MaterialTheme.colorScheme.onSurfaceVariant, modifier = Modifier.size(20.dp))');
lines.push('                    }');
lines.push('                    DropdownMenu(expanded = showMore, onDismissRequest = { showMore = false }) {');
lines.push('                        onPromote?.let {');
lines.push('                            DropdownMenuItem(text = { Text("Promote") }, leadingIcon = { Icon(Icons.AutoMirrored.Filled.TrendingUp, null, modifier = Modifier.size(18.dp)) }, onClick = { showMore = false; it() })');
lines.push('                        }');
lines.push('                        onShare?.let {');
lines.push('                            DropdownMenuItem(text = { Text("Share") }, leadingIcon = { Icon(Icons.Filled.Share, null, modifier = Modifier.size(18.dp)) }, onClick = { showMore = false; it() })');
lines.push('                        }');
lines.push('                    }');
lines.push('                }');
lines.push('            }');
lines.push('            if (item.displayContent.isNotBlank()) {');
lines.push('                Text(');
lines.push('                    text = item.displayContent,');
lines.push('                    fontSize = 14.sp,');
lines.push('                    color = MaterialTheme.colorScheme.onSurfaceVariant,');
lines.push('                    maxLines = if (expanded) Int.MAX_VALUE else 3,');
lines.push('                    overflow = if (expanded) TextOverflow.Visible else TextOverflow.Ellipsis,');
lines.push('                )');
lines.push('                if (item.displayContent.length > 100) {');
lines.push('                    Text(');
lines.push('                        text = if (expanded) "Show less" else "Read more",');
lines.push('                        fontSize = 12.sp,');
lines.push('                        color = MaterialTheme.colorScheme.primary,');
lines.push('                        fontWeight = FontWeight.SemiBold,');
lines.push('                        modifier = Modifier.clickable { expanded = !expanded }.padding(top = 4.dp),');
lines.push('                    )');
lines.push('                }');
lines.push('            }');
lines.push('            if (!item.categoryName.isNullOrBlank()) {');
lines.push('                Surface(shape = RoundedCornerShape(6.dp), color = Color(0xFF6366F1).copy(alpha = 0.1f)) {');
lines.push('                    Text(item.categoryName, fontSize = 11.sp, color = Color(0xFF6366F1), fontWeight = FontWeight.Medium, modifier = Modifier.padding(horizontal = 8.dp, vertical = 3.dp))');
lines.push('                }');
lines.push('            }');
lines.push('            FlowRow(');
lines.push('                modifier = Modifier.fillMaxWidth(),');
lines.push('                horizontalArrangement = Arrangement.spacedBy(6.dp),');
lines.push('                verticalArrangement = Arrangement.spacedBy(4.dp),');
lines.push('            ) {');
lines.push('                Surface(');
lines.push('                    shape = RoundedCornerShape(20.dp),');
lines.push('                    color = if (localLiked) Color(0xFFEF4444).copy(alpha = 0.12f) else MaterialTheme.colorScheme.surfaceVariant,');
lines.push('                    modifier = Modifier.clickable { localLiked = !localLiked; haptic.performHapticFeedback(HapticFeedbackType.LongPress) },');
lines.push('                ) {');
lines.push('                    Row(Modifier.padding(horizontal = 10.dp, vertical = 5.dp), horizontalArrangement = Arrangement.spacedBy(4.dp), verticalAlignment = Alignment.CenterVertically) {');
lines.push('                        Icon(if (localLiked) Icons.Default.Favorite else Icons.Default.FavoriteBorder, null,');
lines.push('                            tint = if (localLiked) Color(0xFFEF4444) else MaterialTheme.colorScheme.onSurfaceVariant,');
lines.push('                            modifier = Modifier.size(14.dp).scale(if (localLiked) likeScale else 1f),');
lines.push('                        )');
lines.push('                        Text(if (localLiked) "Liked" else "Like", fontSize = 11.sp, fontWeight = FontWeight.Medium,');
lines.push('                            color = if (localLiked) Color(0xFFEF4444) else MaterialTheme.colorScheme.onSurfaceVariant,');
lines.push('                        )');
lines.push('                    }');
lines.push('                }');
lines.push('                Surface(');
lines.push('                    shape = RoundedCornerShape(20.dp),');
lines.push('                    color = MaterialTheme.colorScheme.surfaceVariant,');
lines.push('                    modifier = Modifier.clickable {');
lines.push('                        val si = Intent(Intent.ACTION_SEND).apply {');
lines.push('                            type = "text/plain"');
lines.push('                            putExtra(Intent.EXTRA_TEXT, "Check out this post on MHub: " + (item.title ?: item.displayContent.take(80)))');
lines.push('                        }');
lines.push('                        context.startActivity(Intent.createChooser(si, "Share via"))');
lines.push('                    },');
lines.push('                ) {');
lines.push('                    Row(Modifier.padding(horizontal = 10.dp, vertical = 5.dp), horizontalArrangement = Arrangement.spacedBy(4.dp), verticalAlignment = Alignment.CenterVertically) {');
lines.push('                        Icon(Icons.Outlined.Share, null, tint = MaterialTheme.colorScheme.onSurfaceVariant, modifier = Modifier.size(14.dp))');
lines.push('                        Text("Share", fontSize = 11.sp, fontWeight = FontWeight.Medium, color = MaterialTheme.colorScheme.onSurfaceVariant)');
lines.push('                    }');
lines.push('                }');
lines.push('                if (item.effectiveViews > 0) {');
lines.push('                    Surface(shape = RoundedCornerShape(20.dp), color = MaterialTheme.colorScheme.surfaceVariant) {');
lines.push('                        Row(Modifier.padding(horizontal = 10.dp, vertical = 5.dp), horizontalArrangement = Arrangement.spacedBy(4.dp), verticalAlignment = Alignment.CenterVertically) {');
lines.push('                            Icon(Icons.Default.Visibility, null, tint = MaterialTheme.colorScheme.onSurfaceVariant, modifier = Modifier.size(14.dp))');
lines.push('                            Text("$' + '{item.viewCount ?: 0}", fontSize = 11.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)');
lines.push('                        }');
lines.push('                    }');
lines.push('                }');
lines.push('            }');
lines.push('        }');
lines.push('    }');
lines.push('}');

var newCard = '\r\n' + lines.join('\r\n') + '\r\n';
var oldLen = end - start;
console.log('Old length: ' + oldLen + ', New length: ' + newCard.length);

c = c.substring(0, start) + newCard + c.substring(end);

fs.writeFileSync(path, c);
console.log('Done');
