org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
kotlin.code.style=official
kotlin.incremental=true

# KSP
ksp.incremental=true

# Dagger Hilt KSP FastInit - resolves FileAlreadyExistsException with Room
dagger.fastInit=enabled
